version: 2.1

orbs:
  gradle: circleci/gradle@4.2.0

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:21.0
  renovate:
    docker:
      - image: renovate/renovate:latest

jobs:
  run-lint:
    executor: openjdk
    steps:
      - checkout
      - gradle/with_cache:
          deps_checksum_file: build.gradle.kts
          steps:
            - run: ./gradlew check
  activate-renovatebot:
    executor: renovate
    steps:
      - run: renovate

workflows:
  code-analysis:
    jobs:
      - run-lint
      - activate-renovatebot
