package com.hendraanggrian.pages

import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.SetProperty

interface DeployResourcesSpec {
    /**
     * Unchanged resources that is copied from jar.
     * This list contains file paths.
     */
    val staticResourcesSet: SetProperty<String>

    /**
     * Custom resources that is generated by code.
     * This map has filepath as key and content as value.
     */
    val dynamicResourcesMap: MapProperty<Pair<String, String>, String>

    /**
     * Output directory of webpages and resources.
     * Default is `$projectDir/build/pages`.
     */
    val outputDirectory: DirectoryProperty
}
