package com.hendraanggrian.pages

import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.w3c.dom.Document

/** A specification for generating website HTMLs. */
interface DeployPagesSpec {
    /**
     * Custom HTML files that is generated by code.
     * This map has filename as key and whole content as value.
     */
    val pagesMap: MapProperty<String, Document>

    /**
     * Output directory of webpages and resources.
     * Default is `$projectDir/build/pages`.
     */
    val outputDirectory: DirectoryProperty
}
