package com.hendraanggrian.pages

import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.SetProperty
import org.w3c.dom.Document

/** A specification for generating webpages and their resources. */
interface DeployPageSpec {
    /** Resources that are copied from jar. This list contains file paths. */
    val staticResources: SetProperty<String>

    /** Resources that are generated by code. This map has filepath as key and content as value. */
    val dynamicResources: MapProperty<String, String>

    /**
     * HTML files that are generated by code. This map has filename as key and whole content as
     * value.
     */
    val webpages: MapProperty<String, Document>

    /** Output directory of webpages and resources. Default is `$projectDir/build/pages`. */
    val outputDirectory: DirectoryProperty
}
